on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build JAR
        run: ./gradlew shadowJar

      - name: Archive JAR
        uses: actions/upload-artifact@v4
        with:
          name: jar
          path: build/libs/postie.jar

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run Tests
        run: ./gradlew test

  deploy:
    runs-on: ubuntu-latest
    environment: Development
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: jar
          path: build/libs/

      - name: Deploy to AWS
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          SERVERLESS_STAGE: ${{ secrets.SERVERLESS_STAGE }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: serverless deploy --stage $SERVERLESS_STAGE
